const employeeList = [
    {id: 1,
     fullName: "Someone Serious",
     designation: "",
     gender: "male",
     teamName: "teamA"},
    {id: 2,
     fullName: "Agressive Arbiter",
     designation: "",
     gender: "other",
     teamName: "teamC"},
    {id: 3,
     fullName: "Notorious Notar",
     designation: "",
     gender: "female",
     teamName: "teamA"},
    {id: 4,
     fullName: "Sensible Secreterian",
     designation: "",
     gender: "male",
     teamName: "teamA"},
    {id: 5,
     fullName: "Dancing Developer",
     designation: "",
     gender: "female",
     teamName: "teamB"},
    {id: 6,
     fullName: "Angry Acquisitor",
     designation: "",
     gender: "other",
     teamName: "teamB"},
    {id: 7,
     fullName: "Prepared Printer",
     designation: "",
     gender: "female",
     teamName: "teamC"},
    {id: 8,
     fullName: "Extreme Executive",
     designation: "",
     gender: "male",
     teamName: "teamC"},
];
export default employeeList;