const employeeList = [
    {id: 1,
     fullName: "Someone Serious",
     designation: "Selective sorting of Stuff",
     gender: "male",
     teamName: "teamA"},
    {id: 2,
     fullName: "Agressive Arbiter",
     designation: "Avoiding annoying alerts",
     gender: "other",
     teamName: "teamC"},
    {id: 3,
     fullName: "Notorious Notar",
     designation: "nibbling on nebulous notes ",
     gender: "female",
     teamName: "teamA"},
    {id: 4,
     fullName: "Sensible Secreterian",
     designation: "searching somewhat special sounding syllables",
     gender: "male",
     teamName: "teamA"},
    {id: 5,
     fullName: "Dancing Developer",
     designation: "deleting dirty dependencies",
     gender: "female",
     teamName: "teamB"},
    {id: 6,
     fullName: "Angry Acquisitor",
     designation: "adding artificial agents to ancient agriculture",
     gender: "other",
     teamName: "teamB"},
    {id: 7,
     fullName: "Prepared Printer",
     designation: "pulling paper into perforated parts",
     gender: "female",
     teamName: "teamC"},
    {id: 8,
     fullName: "Extreme Executive",
     designation: "being extreme means not having an alliteration as designation",
     gender: "male",
     teamName: "teamC"},
];
export default employeeList;